import React, { useState, useRef } from 'react';
import { type SpeechSegment } from '../../types';
import SpeechSegmentCard from './SpeechSegmentCard';
import AddScriptModal from './AddScriptModal';

interface ProductScriptViewProps {
  script: SpeechSegment[];
  onEditSegment: (segmentId: string, newText: string) => void;
  onDeleteSegment: (segmentId: string) => void;
  onAddSegment: (text: string) => void;
  onReorderScript: (startIndex: number, endIndex: number) => void;
}

const ProductScriptView = ({ script, onEditSegment, onDeleteSegment, onAddSegment, onReorderScript }: ProductScriptViewProps) => {
  const reversedScript = [...script].reverse();
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  
  const dragItemIndex = useRef<number | null>(null);
  const dragOverItemIndex = useRef<number | null>(null);
  const [dragHighlightIndex, setDragHighlightIndex] = useState<number | null>(null);

  const handleDragStart = (e: React.DragEvent<HTMLDivElement>, index: number) => {
    dragItemIndex.current = index;
    // Hides the default ghost image
    if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = 'move';
        e.dataTransfer.setData('text/html', ''); 
    }
  };

  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>, index: number) => {
    e.preventDefault();
    const targetSegment = reversedScript[index];
    if (targetSegment?.status === 'queued') {
      dragOverItemIndex.current = index;
      setDragHighlightIndex(index);
    }
  };

  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setDragHighlightIndex(null);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    if (dragItemIndex.current !== null && dragOverItemIndex.current !== null && dragItemIndex.current !== dragOverItemIndex.current) {
      const scriptLength = script.length;
      const originalDragIndex = scriptLength - 1 - dragItemIndex.current;
      const originalDropIndex = scriptLength - 1 - dragOverItemIndex.current;
      onReorderScript(originalDragIndex, originalDropIndex);
    }
    dragItemIndex.current = null;
    dragOverItemIndex.current = null;
    setDragHighlightIndex(null);
  };
  
  const handleDragEnd = () => {
    dragItemIndex.current = null;
    dragOverItemIndex.current = null;
    setDragHighlightIndex(null);
  };

  return (
    <>
        <div className="h-full flex flex-col overflow-hidden p-4">
            <div className="flex-shrink-0 mb-4 flex justify-between items-center">
                <div>
                    <h3 className="text-lg font-bold text-text-light">Product Script</h3>
                    <p className="text-sm text-text-dark">Speech Segments generated by AI.</p>
                </div>
                <button 
                    onClick={() => setIsAddModalOpen(true)}
                    className="flex items-center space-x-1.5 text-sm text-accent hover:text-accent-hover font-semibold transition-colors"
                >
                     <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>
                     <span>Add Script</span>
                </button>
            </div>
            <div className="flex-grow min-h-0 overflow-y-auto space-y-3 pr-2">
                {reversedScript.length > 0 ? (
                    reversedScript.map((segment, index) => (
                        <SpeechSegmentCard 
                            key={segment.id} 
                            segment={segment} 
                            index={reversedScript.length - index} 
                            onEdit={onEditSegment}
                            onDelete={onDeleteSegment}
                            isDragOver={dragHighlightIndex === index}
                            onDragStart={(e) => handleDragStart(e, index)}
                            onDragEnter={(e) => handleDragEnter(e, index)}
                            onDragLeave={handleDragLeave}
                            onDrop={handleDrop}
                            onDragEnd={handleDragEnd}
                        />
                    ))
                ) : (
                    <div className="text-center text-text-dark pt-10">
                        <p>Generating script...</p>
                    </div>
                )}
            </div>
        </div>
        {isAddModalOpen && (
            <AddScriptModal 
                onClose={() => setIsAddModalOpen(false)}
                onAdd={onAddSegment}
            />
        )}
    </>
  );
};

export default ProductScriptView;